when:
  - event: [push, pull_request]

steps:
  - name: install
    image: oven/bun:1.4.2-alpine
    environment:
      GITHUB_PACKAGES_TOKEN:
        from_secret: github_packages_token
    commands:
      - printf '//npm.pkg.github.com/:_authToken=%s\n' "$${GITHUB_PACKAGES_TOKEN}" > /root/.npmrc
      - bun install --frozen-lockfile
      - rm -f /root/.npmrc

  - name: check
    image: oven/bun:1.4.2-alpine
    commands:
      - bun run check

  - name: docker
    image: moby/buildkit:v0.33.0-rootless
    environment:
      BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
      GITHUB_PACKAGES_TOKEN:
        from_secret: github_packages_token
    commands:
      - >
        buildctl-daemonless.sh build
        --frontend dockerfile.v0
        --local context=.
        --local dockerfile=.
        --secret id=github_packages_token,env=GITHUB_PACKAGES_TOKEN
        --output type=oci,dest=/tmp/wissem-home.tar
